# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 20
add_newline = false

[character]
format = "[λ](blue) "
success_symbol = "[λ](green) "
error_symbol = "[λ](red) "

[cmd_duration]
min_time = 50

[directory]
truncation_length = 10
truncate_to_repo = false

[nix_shell]
impure_msg = "[impure shell](bold red)"
pure_msg = "[pure shell](bold green)"
format = 'via [❄️ $state( \($name\))](bold blue) '


[status]
disabled = false
